// priority: 90
ServerEvents.recipes(event=>{
     event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_01_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('3x gtceu:raw_bentonite')
        .itemOutputs('2x gtceu:raw_magnesite')
        .itemOutputs('2x gtceu:raw_olivine')
        .itemOutputs('gtceu:raw_glauconite_sand')
        .circuit(1)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_02_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('3x gtceu:raw_almandine')
        .itemOutputs('2x gtceu:raw_pyrope')
        .itemOutputs('gtceu:raw_sapphire')
        .itemOutputs('gtceu:raw_green_sapphire')
        .circuit(2)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_03_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('5x gtceu:raw_goethite')
        .itemOutputs('2x gtceu:raw_yellow_limonite')
        .itemOutputs('2x gtceu:raw_hematite')
        .itemOutputs('gtceu:raw_malachite')
        .circuit(3)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_04_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('3x gtceu:raw_soapstone')
        .itemOutputs('2x gtceu:raw_talc')
        .itemOutputs('2x gtceu:raw_glauconite_sand')
        .itemOutputs('gtceu:raw_pentlandite')
        .circuit(4)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_05_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('3x gtceu:raw_grossular')
        .itemOutputs('2x gtceu:raw_spessartine')
        .itemOutputs('2x gtceu:raw_pyrolusite')
        .itemOutputs('gtceu:raw_tantalite')
        .circuit(5)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_06_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('5x gtceu:raw_chalcopyrite')
        .itemOutputs('2x gtceu:raw_zeolite')
        .itemOutputs('2x gtceu:raw_cassiterite')
        .itemOutputs('gtceu:raw_realgar')
        .circuit(6)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_07_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('3x gtceu:raw_coal')
        .itemOutputs('2x gtceu:small_anthracite_coal_dust')
        .circuit(7)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_08_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('5x gtceu:raw_chalcopyrite')
        .itemOutputs('2x minecraft:raw_iron')
        .itemOutputs('2x gtceu:raw_pyrite')
        .itemOutputs('2x minecraft:raw_copper')
        .circuit(8)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_09_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('3x gtceu:raw_magnetite')
        .itemOutputs('2x gtceu:raw_vanadium_magnetite')
        .itemOutputs('gtceu:raw_chromite')
        .itemOutputs('minecraft:raw_gold')
        .circuit(9)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_10_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('3x gtceu:raw_lazurite')
        .itemOutputs('2x gtceu:raw_sodalite')
        .itemOutputs('2x gtceu:raw_lapis')
        .itemOutputs('gtceu:raw_calcite')
        .circuit(10)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_11_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('3x gtceu:raw_galena')
        .itemOutputs('2x gtceu:raw_silver')
        // .itemOutputs('gtceu:raw_lead')
        .circuit(11)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_12_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('3x gtceu:raw_kyanite')
        .itemOutputs('2x gtceu:raw_mica')
        .itemOutputs('2x gtceu:raw_bauxite')
        .itemOutputs('gtceu:raw_pollucite')
        .circuit(12)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_13_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('4x gtceu:raw_tin')
        .itemOutputs('2x gtceu:raw_cassiterite')
        .circuit(13)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_14_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('3x gtceu:raw_red_garnet')
        .itemOutputs('2x gtceu:raw_yellow_garnet')
        .itemOutputs('2x gtceu:raw_amethyst')
        .itemOutputs('gtceu:raw_opal')
        .circuit(14)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_15_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('3x gtceu:raw_basaltic_mineral_sand')
        .itemOutputs('2x gtceu:raw_granitic_mineral_sand')
        .itemOutputs('2x gtceu:raw_fullers_earth')
        .itemOutputs('gtceu:raw_gypsum')
        .itemOutputs('gtceu:raw_cryolite')
        .circuit(15)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_16_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('3x gtceu:raw_rock_salt')
        .itemOutputs('2x gtceu:raw_salt')
        .itemOutputs('gtceu:raw_lepidolite')
        .itemOutputs('gtceu:raw_spodumene')
        .circuit(16)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_17_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('3x gtceu:raw_redstone')
        .itemOutputs('2x gtceu:raw_ruby')
        .itemOutputs('gtceu:raw_cinnabar')
        .circuit(17)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_18_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('3x gtceu:raw_apatite')
        .itemOutputs('2x gtceu:raw_tricalcium_phosphate')
        .itemOutputs('gtceu:raw_pyrochlore')
        .circuit(18)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_19_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('3x gtceu:raw_cassiterite_sand')
        .itemOutputs('2x gtceu:raw_garnet_sand')
        .itemOutputs('2x gtceu:raw_asbestos')
        .itemOutputs('gtceu:raw_diatomite')
        .itemOutputs('gtceu:bi2o3_dust')
        .circuit(19)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_20_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('6x gtceu:raw_oilsands')
        .circuit(20)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_21_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('7x gtceu:raw_graphite')
        .itemOutputs('3x gtceu:raw_diamond')
        .itemOutputs('gtceu:raw_coal')
        .circuit(21)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_22_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('3x gtceu:raw_garnierite')
        .itemOutputs('2x gtceu:raw_nickel')
        .itemOutputs('2x gtceu:raw_cobaltite')
        .itemOutputs('gtceu:raw_pentlandite')
        .circuit(22)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_23_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('3x gtceu:raw_sulfur')
        .itemOutputs('2x gtceu:raw_pyrite')
        .itemOutputs('2x gtceu:raw_emerald')
        .itemOutputs('gtceu:raw_sphalerite')
        .circuit(23)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_24_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('4x gtceu:raw_tetrahedrite')
        .itemOutputs('2x minecraft:raw_copper')
        .itemOutputs('gtceu:raw_stibnite')
        .circuit(24)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_25_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('3x gtceu:raw_saltpeter')
        .itemOutputs('2x gtceu:raw_diatomite')
        .itemOutputs('2x gtceu:raw_electrotine')
        .itemOutputs('gtceu:raw_alunite')
        .circuit(25)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_00_overworld')
        .notConsumable('gtceu:overworld_marker')
        .itemOutputs('64x minecraft:cobblestone')
        .itemOutputs('64x minecraft:gravel')
        .itemOutputs('64x minecraft:sand')
        .itemOutputs('16x minecraft:granite')
        .itemOutputs('16x minecraft:diorite')
        .itemOutputs('16x minecraft:andesite')
        .chancedOutput('ae2:not_so_mysterious_cube',10,0)
        .chancedOutput('gtceu:overworld_marker',10,0)
        .circuit(0)
        .duration(15)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_32_overworld')
        .notConsumable('gtceu:overworld_marker')
        .chancedOutput('gtceu:rubber_sapling',1000,0)
        .chancedOutput('sugar_cane',1000,0)
        .circuit(32)
        .duration(15)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_0_ae2')
        .notConsumable('ae2:not_so_mysterious_cube')
        .itemOutputs('3x gtceu:raw_certus_quartz')
        .itemOutputs('3x gtceu:raw_quartzite')
        .itemOutputs('3x gtceu:raw_nether_quartz')
        .itemOutputs('3x ae2:sky_dust')
        .itemOutputs('gtceu:caf2_dust')
        .itemOutputs('minecraft:glowstone_dust')
        .chancedOutput('ae2:mysterious_cube',50,0)
        .duration(20)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_00_moon')
        .notConsumable('mcgougou:moon_marker')
        .itemOutputs('16x ad_astra:moon_stone')
        .chancedOutput('mcgougou:moon_marker',10,0)
        .circuit(0)
        .duration(15)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_01_moon')
        .notConsumable('mcgougou:moon_marker')
        .itemOutputs('2x gtceu:raw_bauxite')
        .itemOutputs('gtceu:raw_ilmenite')
        .circuit(1)
        .duration(30)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_02_moon')
        .notConsumable('mcgougou:moon_marker')
        .itemOutputs('3x gtceu:raw_bastnasite')
        .itemOutputs('gtceu:raw_monazite')
        .circuit(2)
        .duration(30)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_03_moon')
        .notConsumable('mcgougou:moon_marker')
        .itemOutputs('3x gtceu:raw_bornite')
        .itemOutputs('2x gtceu:raw_cooperite')
        .circuit(3)
        .duration(30)
        .EUt(8);
event.recipes.gtceu.ore_breaker_recipe('mcgougou:ore_breaker_00_neth')
        .notConsumable('gtceu:the_nether_marker')
        .itemOutputs('64x minecraft:netherrack')
        .itemOutputs('64x minecraft:soul_sand')
        .itemOutputs('64x minecraft:glowstone_dust')
        .itemOutputs('8x minecraft:nether_wart')
        .itemOutputs()
        .itemOutputs()
        .chancedOutput('gtceu:the_nether_marker',10,0)
        .circuit(0)
        .duration(15)
        .EUt(8);
event.recipes.gtceu.monster_killer_recipe('mcgougou:monster_killer_recipe')
.itemOutputs('minecraft:experience_bottle')
        .chancedOutput('minecraft:rotten_flesh',5000,0)
        .chancedOutput('minecraft:bone',4000,0)
        .chancedOutput('minecraft:arrow',2000,0)
        .chancedOutput('minecraft:gunpowder',5000,0)
        .chancedOutput('minecraft:ender_pearl',2000,0)
        .chancedOutput('minecraft:spider_eye',2000,0)
        .chancedOutput('minecraft:string',5000,0)
        .chancedOutput('minecraft:wither_skeleton_skull',100,100)
        .circuit(1)
        .duration(10)
        .EUt(16);
event.recipes.gtceu.monster_killer_recipe('mcgougou:monster_killer_recipe_2')
.itemInputs('4x minecraft:soul_sand')
.itemInputs('3x minecraft:wither_skeleton_skull')
.itemOutputs('minecraft:nether_star')
        .circuit(2)
        .duration(30)
        .EUt(500);
event.recipes.gtceu.mixer('mcgougou:mixer_al2o3_cryshenmegui_recipe')
        .itemInputs('gtceu:sapphire_dust')
        .itemInputs('gtceu:cryolite_dust')
        .itemOutputs('gtceu:aluminium_oxide_with_cryolite_dust')
        .circuit(1)
        .duration(10)
        .EUt(30);
event.recipes.gtceu.mixer('mcgougou:mixer_al2o3_cryshenmegui_2_recipe')
        .itemInputs('gtceu:green_sapphire_dust')
        .itemInputs('gtceu:cryolite_dust')
        .itemOutputs('gtceu:aluminium_oxide_with_cryolite_dust')
        .circuit(2)
        .duration(10)
        .EUt(30);
event.recipes.gtceu.mixer('mcgougou:mixer_al2o3_cryshenmegui_3_recipe')
        .itemInputs('gtceu:aluminum_oxide_dust')
        .itemInputs('gtceu:cryolite_dust')
        .itemOutputs('gtceu:aluminium_oxide_with_cryolite_dust')
        .circuit(3)
        .duration(10)
        .EUt(30);
event.recipes.gtceu.mixer('mcgougou:mixer_tiechun_recipe')
        .itemInputs('10x gtceu:magnetite_dust')
        .itemInputs('3x gtceu:tiny_sapphire_dust')
        .itemInputs('gtceu:tiny_potash_dust')
        .itemInputs('gtceu:tiny_quicklime_dust')
        .itemOutputs('8x gtceu:iron_based_catalyst_dust')
        .circuit(1)
        .duration(50)
        .EUt(60);
event.recipes.gtceu.circuit_assembler('mcgougou:circuit_assembler_gongcheng_recipe')
        .notConsumable('ae2:mysterious_cube')
        .itemInputs('4x gtceu:diamond_plate')
        .itemInputs('4x ae2:silicon')
        .inputFluids(Fluid.of("gtceu:redstone",2304))
        .itemOutputs('4x ae2:engineering_processor')
        .circuit(1)
        .duration(5)
        .EUt(30);
event.recipes.gtceu.circuit_assembler('mcgougou:circuit_assembler_luoji_recipe')
        .notConsumable('ae2:mysterious_cube')
        .itemInputs('4x gtceu:gold_plate')
        .itemInputs('4x ae2:silicon')
        .inputFluids(Fluid.of("gtceu:redstone",2304))
        .itemOutputs('4x ae2:logic_processor')
        .circuit(2)
        .duration(5)
        .EUt(30);
event.recipes.gtceu.circuit_assembler('mcgougou:circuit_assembler_yunsuan_recipe')
        .notConsumable('ae2:mysterious_cube')
        .itemInputs('4x gtceu:certus_quartz_plate')
        .itemInputs('4x ae2:silicon')
        .inputFluids(Fluid.of("gtceu:redstone",2304))
        .itemOutputs('4x ae2:calculation_processor')
        .circuit(3)
        .duration(5)
        .EUt(30);
// event.recipes.gtceu.mixer('mcgougou:mixer_al2o3_mno2_recipe')
//         .itemInputs('gtceu:pyrolusite_dust')
//         .itemInputs('gtceu:aluminium_dust')
//         .itemOutputs('2x gtceu:aluminium_with_pyrolusite_dust')
//         .circuit(2)
//         .duration(30)
//         .EUt(30);
event.recipes.gtceu.mixer('mcgougou:mixer_ag_cu_to_tuag')
        .itemInputs('gtceu:tiny_silver_dust')
        .itemInputs('64x gtceu:copper_dust')
        .itemInputs('47x gtceu:copper_dust')
        .itemOutputs('64x gtceu:tuag_dust')
        .circuit(5)
        .duration(1200)
        .EUt(30);
event.recipes.gtceu.electrolyzer('mcgougou:electro_al2o3_cryshenmegui_recipe')
        .inputFluids(Fluid.of('gtceu:aluminium_oxide_with_cryolite',720))
        .itemOutputs('2x gtceu:aluminium_dust')
        .itemOutputs('5x gtceu:cryolite_dust')
        .outputFluids(Fluid.of("gtceu:oxygen",3000))
        .duration(80)
        .EUt(30);
event.recipes.gtceu.electrolyzer('mcgougou:electro_kcl_solute_recipe')
        .inputFluids(Fluid.of('gtceu:rock_salt_solution',2000))
        .itemOutputs('gtceu:potassium_hydroxide_dust')
        .outputFluids(Fluid.of("gtceu:hydrogen",1000))
        .outputFluids(Fluid.of("gtceu:chlorine",1000))
        .duration(30)
        .EUt(30);
event.recipes.gtceu.electrolyzer('mcgougou:electro_mnso4tomn')
        .inputFluids(Fluid.of('gtceu:manganese_sulfate_solution',2000))
        .itemOutputs('gtceu:manganese_dust')
        .outputFluids(Fluid.of("gtceu:oxygen",500))
        .outputFluids(Fluid.of("gtceu:diluted_sulfuric_acid",1500))
        .duration(80)
        .EUt(60);
event.recipes.gtceu.electrolyzer('mcgougou:electro_water')
        .notConsumable('gtceu:potassium_hydroxide_dust')
        .inputFluids(Fluid.of('water',1000))
        .outputFluids(Fluid.of("gtceu:oxygen",1000))
        .outputFluids(Fluid.of("gtceu:hydrogen",2000))
        .circuit(1)
        .duration(25)
        .EUt(30);
event.recipes.gtceu.assembler('mcgougou:assembler_circuit_recipe_ulv')
        .itemInputs('#gtceu:circuits/ulv')
        .itemOutputs('mcgougou:ulv_universal_circuit')
        .circuit(32)
        .duration(1)
        .EUt(1);
event.recipes.gtceu.assembler('mcgougou:assembler_circuit_recipe_lv')
        .itemInputs('#gtceu:circuits/lv')
        .itemOutputs('mcgougou:lv_universal_circuit')
        .circuit(32)
        .duration(1)
        .EUt(1);
event.recipes.gtceu.assembler('mcgougou:assembler_circuit_recipe_mv')
        .itemInputs('#gtceu:circuits/mv')
        .itemOutputs('mcgougou:mv_universal_circuit')
        .circuit(32)
        .duration(1)
        .EUt(1);
event.recipes.gtceu.assembler('mcgougou:assembler_circuit_recipe_hv')
        .itemInputs('#gtceu:circuits/hv')
        .itemOutputs('mcgougou:hv_universal_circuit')
        .circuit(32)
        .duration(1)
        .EUt(1);
event.recipes.gtceu.assembler('mcgougou:assembler_circuit_recipe_ev')
        .itemInputs('#gtceu:circuits/ev')
        .itemOutputs('mcgougou:ev_universal_circuit')
        .circuit(32)
        .duration(1)
        .EUt(1);
event.recipes.gtceu.assembler('mcgougou:assembler_circuit_recipe_iv')
        .itemInputs('#gtceu:circuits/iv')
        .itemOutputs('mcgougou:iv_universal_circuit')
        .circuit(32)
        .duration(1)
        .EUt(1);
event.recipes.gtceu.assembler('mcgougou:assembler_circuit_recipe_luv')
        .itemInputs('#gtceu:circuits/luv')
        .itemOutputs('mcgougou:luv_universal_circuit')
        .circuit(32)
        .duration(1)
        .EUt(1);
event.recipes.gtceu.assembler('mcgougou:assembler_circuit_recipe_zpm')
        .itemInputs('#gtceu:circuits/zpm')
        .itemOutputs('mcgougou:zpm_universal_circuit')
        .circuit(32)
        .duration(1)
        .EUt(1);
event.recipes.gtceu.assembler('mcgougou:assembler_circuit_recipe_uv')
        .itemInputs('#gtceu:circuits/uv')
        .itemOutputs('mcgougou:uv_universal_circuit')
        .circuit(32)
        .duration(1)
        .EUt(1);
event.recipes.gtceu.assembler('mcgougou:assembler_circuit_recipe_uhv')
        .itemInputs('#gtceu:circuits/uhv')
        .itemOutputs('mcgougou:uhv_universal_circuit')
        .circuit(32)
        .duration(1)
        .EUt(1);
// event.recipes.gtceu.chemical_reactor('mcgougou:chemical_al_mno2_to_alo_mn')
//         .itemInputs('6x gtceu:aluminium_with_pyrolusite_dust')
//         .itemOutputs('2x gtceu:manganese_dust')
//         .itemOutputs('2x gtceu:sapphire_dust')
//         .circuit(2)
//         .duration(200)
//         .EUt(31);
event.recipes.gtceu.autoclave('mcgougou:chemical_mn_p_to_mnp')
        .itemInputs('gtceu:manganese_dust')
        .itemInputs('gtceu:phosphorus_dust')
        .itemOutputs('gtceu:manganese_phosphide_dust')
        .duration(40)
        .EUt(24);
event.recipes.gtceu.chemical_bath('mcgougou:bath_kcl_to_its_solute')
        .itemInputs('gtceu:rock_salt_dust')
        .inputFluids(Fluid.of("water",1000))
        .outputFluids(Fluid.of("gtceu:rock_salt_solution",2000))
        .duration(20)
        .EUt(24);
event.recipes.gtceu.chemical_reactor('mcgougou:chemical_mno_to_mnso4')
        .itemInputs('gtceu:manganese_monoxide_dust')
        .inputFluids(Fluid.of("gtceu:sulfuric_acid",1000))
        .outputFluids(Fluid.of("gtceu:manganese_sulfate_solution",2000))
        .circuit(2)
        .duration(20)
        .EUt(24);
event.recipes.gtceu.chemical_reactor('mcgougou:chemical_satssy_charge')
        .itemInputs('64x gtceu:certus_quartz_gem')
        .itemOutputs('64x ae2:charged_certus_quartz_crystal')
        .circuit(1)
        .duration(10)
        .EUt(30);
event.recipes.gtceu.assembler('mcgougou:chemical_fluix_make')
        .itemInputs('16x ae2:charged_certus_quartz_crystal')
        .itemInputs('16x minecraft:redstone')
        .itemInputs('16x minecraft:quartz')
        .itemOutputs('64x ae2:fluix_crystal')
        .duration(10)
        .EUt(30);
event.recipes.gtceu.chemical_reactor('mcgougou:chemical_v2_v3_to_v5')
        .itemInputs('3x gtceu:vanadium_slag_dust')
        .itemInputs('gtceu:soda_ash_dust')
        .inputFluids(Fluid.of("gtceu:oxygen",1000))
        .itemOutputs('gtceu:vanadium_leaching_residue_dust')
        .outputFluids(Fluid.of("gtceu:carbon_dioxide",1000))
        .outputFluids(Fluid.of("gtceu:vanadium_containing_leaching_solution",2000))
        //.circuit(1)
        .duration(20)
        .EUt(24);
event.recipes.gtceu.macerator('mcgougou:fensuiai_funoadunf')
        .itemInputs('ae2:fluix_crystal')
        .itemOutputs('ae2:fluix_dust')
        .duration(2)
        .EUt(2);
event.recipes.gtceu.compressor('mcgougou:press_mnp_to_nugget')
        .itemInputs('gtceu:tiny_manganese_phosphide_dust')
        .itemOutputs('gtceu:manganese_phosphide_nugget')
        .duration(20)
        .EUt(24);
event.recipes.gtceu.compressor('mcgougou:press_v2o5_to_blocks')
        .itemInputs('9x gtceu:vanadium_pentoxide_dust')
        .itemOutputs('gtceu:vanadium_pentoxide_block')
        .duration(20)
        .EUt(60);
event.recipes.gtceu.fluid_driller_recipe('mcgougou:drilling_overworld_01')
        .notConsumable('gtceu:overworld_marker')
        .outputFluids(Fluid.of("gtceu:oil_medium",1000))
        .duration(10)
        .circuit(1)
        .EUt(64);
event.recipes.gtceu.fluid_driller_recipe('mcgougou:drilling_overworld_02')
        .notConsumable('gtceu:overworld_marker')
        .outputFluids(Fluid.of("gtceu:salt_water",1000))
        .duration(10)
        .circuit(2)
        .EUt(64);

event.recipes.gtceu.fluid_driller_recipe('mcgougou:drilling_overworld_03')
        .notConsumable('gtceu:overworld_marker')
        .outputFluids(Fluid.of("gtceu:oil_heavy",1000))
        .duration(10)
        .circuit(3)
        .EUt(64);
event.recipes.gtceu.fluid_driller_recipe('mcgougou:drilling_overworld_04')
        .notConsumable('gtceu:overworld_marker')
        .outputFluids(Fluid.of("gtceu:oil",1000))
        .duration(10)
        .circuit(4)
        .EUt(64);
event.recipes.gtceu.fluid_driller_recipe('mcgougou:drilling_overworld_05')
        .notConsumable('gtceu:overworld_marker')
        .outputFluids(Fluid.of("gtceu:natural_gas",1000))
        .duration(10)
        .circuit(5)
        .EUt(64);

event.recipes.gtceu.fluid_driller_recipe('mcgougou:drilling_overworld_06')
        .notConsumable('gtceu:overworld_marker')
        .outputFluids(Fluid.of("gtceu:oil_light",1000))
        .duration(10)
        .circuit(6)
        .EUt(64);
event.recipes.gtceu.fluid_driller_recipe('mcgougou:drilling_net_1')
        .notConsumable('gtceu:the_nether_marker')
        .outputFluids(Fluid.of("lava",1000))
        .duration(10)
        .circuit(1)
        .EUt(64);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_vfe_tofe_v')
        .itemInputs('gtceu:vanadium_magnetite_dust')
        .itemInputs('4x gtceu:carbon_dust')
        .itemOutputs('minecraft:iron_ingot')
        .itemOutputs('gtceu:vanadium_slag_dust')
        .blastFurnaceTemp(1800)
        .outputFluids(Fluid.of("gtceu:carbon_monoxide",4000))
        .duration(50)
        .circuit(6)
        .EUt(78);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_koh_to_k2o')
        .itemInputs('2x gtceu:potassium_hydroxide_dust')
        .itemOutputs('gtceu:potash_dust')
        .inputFluids(Fluid.of("gtceu:nitrogen",500))
        .blastFurnaceTemp(800)
        .outputFluids(Fluid.of("gtceu:steam",1000))
        .duration(20)
        .circuit(1)
        .EUt(64);

event.recipes.gtceu.nh3_factory_recipe('mcgougou:nh3_1_recipe')
        .notConsumable("64x gtceu:iron_based_catalyst_dust")
        .inputFluids(Fluid.of("gtceu:hydrogen",300000))
        .inputFluids(Fluid.of("gtceu:nitrogen",100000))
        .outputFluids(Fluid.of("gtceu:ammonia",15000))
        .duration(750)
        .circuit(1)
        .EUt(120);
event.recipes.gtceu.nh3_factory_recipe('mcgougou:nh3_2_recipe')
        .notConsumable("64x gtceu:iron_based_catalyst_dust")
        .inputFluids(Fluid.of("gtceu:hydrogen",300000))
        .inputFluids(Fluid.of("gtceu:nitrogen",100000))
        .outputFluids(Fluid.of("gtceu:ammonia",27750))
        .duration(1500)
        .circuit(2)
        .EUt(120);
event.recipes.gtceu.nh3_factory_recipe('mcgougou:nh3_3_recipe')
        .notConsumable("64x gtceu:iron_based_catalyst_dust")
        .inputFluids(Fluid.of("gtceu:hydrogen",300000))
        .inputFluids(Fluid.of("gtceu:nitrogen",100000))
        .outputFluids(Fluid.of("gtceu:ammonia",38588))
        .duration(2250)
        .circuit(3)
        .EUt(120);
event.recipes.gtceu.nh3_factory_recipe('mcgougou:nh3_4_recipe')
        .notConsumable("64x gtceu:iron_based_catalyst_dust")
        .inputFluids(Fluid.of("gtceu:hydrogen",300000))
        .inputFluids(Fluid.of("gtceu:nitrogen",100000))
        .outputFluids(Fluid.of("gtceu:ammonia",47800))
        .duration(3000)
        .circuit(4)
        .EUt(120);
event.recipes.gtceu.nh3_factory_recipe('mcgougou:nh3_5_recipe')
        .notConsumable("64x gtceu:iron_based_catalyst_dust")
        .inputFluids(Fluid.of("gtceu:hydrogen",300000))
        .inputFluids(Fluid.of("gtceu:nitrogen",100000))
        .outputFluids(Fluid.of("gtceu:ammonia",55630))
        .duration(3750)
        .circuit(5)
        .EUt(120);
event.recipes.gtceu.nh3_factory_recipe('mcgougou:nh3_6_recipe')
        .notConsumable("64x gtceu:iron_based_catalyst_dust")
        .inputFluids(Fluid.of("gtceu:hydrogen",300000))
        .inputFluids(Fluid.of("gtceu:nitrogen",100000))
        .outputFluids(Fluid.of("gtceu:ammonia",62286))
        .duration(4500)
        .circuit(6)
        .EUt(120);
event.recipes.gtceu.nh3_factory_recipe('mcgougou:nh3_7_recipe')
        .notConsumable("64x gtceu:iron_based_catalyst_dust")
        .inputFluids(Fluid.of("gtceu:hydrogen",300000))
        .inputFluids(Fluid.of("gtceu:nitrogen",100000))
        .outputFluids(Fluid.of("gtceu:ammonia",67943))
        .duration(5250)
        .circuit(7)
        .EUt(120);
event.recipes.gtceu.nh3_factory_recipe('mcgougou:nh3_8_recipe')
        .notConsumable("64x gtceu:iron_based_catalyst_dust")
        .inputFluids(Fluid.of("gtceu:hydrogen",300000))
        .inputFluids(Fluid.of("gtceu:nitrogen",100000))
        .outputFluids(Fluid.of("gtceu:ammonia",72752))
        .duration(6000)
        .circuit(8)
        .EUt(120);
event.recipes.gtceu.nh3_factory_recipe('mcgougou:nh3_9_recipe')
        .notConsumable("64x gtceu:iron_based_catalyst_dust")
        .inputFluids(Fluid.of("gtceu:hydrogen",300000))
        .inputFluids(Fluid.of("gtceu:nitrogen",100000))
        .outputFluids(Fluid.of("gtceu:ammonia",76839))
        .duration(6750)
        .circuit(9)
        .EUt(120);
event.recipes.gtceu.nh3_factory_recipe('mcgougou:nh3_10_recipe')
        .notConsumable("64x gtceu:iron_based_catalyst_dust")
        .inputFluids(Fluid.of("gtceu:hydrogen",300000))
        .inputFluids(Fluid.of("gtceu:nitrogen",100000))
        .outputFluids(Fluid.of("gtceu:ammonia",80313))
        .duration(7500)
        .circuit(10)
        .EUt(120);

event.recipes.gtceu.air_fenli_recipe('mcgougou:air_1_recipe')
        .inputFluids(Fluid.of("gtceu:air",60000))
        .outputFluids(Fluid.of("gtceu:nitrogen",35000))
        .outputFluids(Fluid.of("gtceu:oxygen",15000))
        .duration(800)
        .circuit(1)
        .EUt(120);
event.recipes.gtceu.chemical_reactor('mcgougou:chemical_nahco3_to_na2co3_recipe')
        .itemInputs('4x gtceu:sodium_bicarbonate_dust')
        .itemOutputs('2x gtceu:soda_ash_dust')
        .outputFluids(Fluid.of("gtceu:steam",2000))
        .outputFluids(Fluid.of("gtceu:carbon_dioxide",2000))
        .duration(10)
        .circuit(1)
        .EUt(50);
event.recipes.gtceu.chemical_reactor('mcgougou:chemical_navo3_to_hvo3_recipe')
        .inputFluids( Fluid.of('gtceu:vanadium_containing_leaching_solution', 2000))
        .inputFluids( Fluid.of('gtceu:carbon_dioxide', 1000))
        .itemOutputs('2x gtceu:salt_dust')
        .itemInputs('2x gtceu:ammonium_chloride_dust')
        .outputFluids( Fluid.of('gtceu:carbon_dioxide', 900))
        .itemOutputs('2x gtceu:ammonium_metavanadate_dust')
        .duration(40)
        .circuit(4)
        .EUt(30);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_nh4vo3_to_v2o5_recipe')
        .itemInputs('4x gtceu:ammonium_metavanadate_dust')
        .itemOutputs('2x gtceu:vanadium_pentoxide_dust')
        .blastFurnaceTemp(800)
        .outputFluids(Fluid.of("gtceu:ammonia",2000))
        .duration(160)
        .circuit(1)
        .EUt(100);

event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_v2o5_tov_recipe')
        .itemInputs('10x gtceu:aluminium_dust')
        .itemInputs('3x gtceu:vanadium_pentoxide_dust')
        .itemOutputs('6x gtceu:vanadium_ingot')
        .itemOutputs('25x gtceu:aluminum_oxide_dust')
        .blastFurnaceTemp(1400)
        .duration(40)
        .circuit(3)
        .EUt(50);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_as4s4_toas203_recipe')
        .itemInputs('4x gtceu:realgar_dust')
        .itemOutputs('5x gtceu:arsenic_trioxide_dust')
        .inputFluids(Fluid.of('gtceu:oxygen', 5000))
        .outputFluids(Fluid.of("gtceu:sulfur_dioxide",2000))
        .blastFurnaceTemp(800)
        .duration(40)
        .circuit(1)
        .EUt(50);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_as203_to_as_recipe')
        .itemInputs('5x gtceu:arsenic_trioxide_dust')
        .itemInputs('3x gtceu:carbon_dust')
        .itemOutputs('2x gtceu:arsenic_dust')
        .inputFluids(Fluid.of('gtceu:nitrogen', 1000))
        .outputFluids(Fluid.of("gtceu:carbon_monoxide",3000))
        .blastFurnaceTemp(1100)
        .duration(50)
        .circuit(1)
        .EUt(70);
event.recipes.gtceu.bayer_recipe('mcgougou:bayer_recipe_as_recipe')
        .itemInputs('32x gtceu:sodium_hydroxide_dust')
        .itemInputs('64x gtceu:bauxite_dust')
        .itemInputs('64x gtceu:bauxite_dust')
        .itemInputs('64x gtceu:bauxite_dust')
        .itemInputs('64x gtceu:bauxite_dust')
        .itemInputs('64x gtceu:bauxite_dust')
        .itemOutputs('64x gtceu:aluminum_hydroxide_dust')
        .itemOutputs('64x gtceu:aluminum_hydroxide_dust')
        .itemOutputs('64x gtceu:aluminum_hydroxide_dust')
        .itemOutputs('64x gtceu:aluminum_hydroxide_dust')
        .itemOutputs('64x gtceu:aluminum_hydroxide_dust')
        .inputFluids(Fluid.of('water', 16000))
        .outputFluids(Fluid.of("gtceu:bayer_solution",16000))
        .duration(400)
        .circuit(1)
        .EUt(50);
event.recipes.gtceu.bayer_recipe('mcgougou:bayer_recipe_as_2_recipe')
        .itemInputs('32x gtceu:sodium_hydroxide_dust')
        .itemInputs('64x gtceu:bauxite_dust')
        .itemInputs('64x gtceu:bauxite_dust')
        .itemInputs('64x gtceu:bauxite_dust')
        .itemInputs('64x gtceu:bauxite_dust')
        .itemInputs('64x gtceu:bauxite_dust')
        .itemOutputs('64x gtceu:aluminum_oxide_dust')
        .itemOutputs('64x gtceu:aluminum_oxide_dust')
        .itemOutputs('32x gtceu:aluminum_oxide_dust')
        .inputFluids(Fluid.of('water', 16000))
        .outputFluids(Fluid.of("gtceu:bayer_solution",16000))
        .duration(700)
        .circuit(2)
        .EUt(50);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_aloh3_to_al203_recipe')
        .itemInputs('4x gtceu:aluminum_hydroxide_dust')
        .itemOutputs('2x gtceu:aluminum_oxide_dust')
        .blastFurnaceTemp(1300)
        .duration(20)
        .circuit(1)
        .EUt(70);
event.recipes.gtceu.mv_generator_recipe('mcgougou:mv_o1_rp')
        .itemInputs('2x gtceu:anthracite_coal_dust')
        .inputFluids( Fluid.of('gtceu:oxygen', 3000))
        .itemOutputs('gtceu:tiny_ash_dust')
        .duration(100)
        .circuit(1)
        .EUt(-2048);
event.recipes.gtceu.mv_generator_recipe('mcgougou:mv_o3_rp')
        .itemInputs('2x gtceu:anthracite_coal_dust')
        .itemOutputs('gtceu:tiny_ash_dust')
        .duration(100)
        .circuit(2)
        .EUt(-512);
event.recipes.gtceu.chemical_reactor('mcgougou:chem_bayer_to_oh3_recipe')
        .inputFluids( Fluid.of('gtceu:bayer_solution', 2000))
        .inputFluids( Fluid.of('gtceu:carbon_dioxide', 2000))
        .itemOutputs('6x gtceu:sodium_bicarbonate_dust')
        .itemOutputs('16x gtceu:al_ga_oh_3_dust')
        .duration(20)
        .circuit(1)
        .EUt(20);
event.recipes.gtceu.chemical_reactor('mcgougou:chem_ga_aloh3_to_caaloh42_recipe')
.itemInputs('16x gtceu:al_ga_oh_3_dust').inputFluids( Fluid.of('gtceu:caoh2_solution', 8000))
.outputFluids(Fluid.of("gtceu:ca_aloh4_solution",8000))
        .itemOutputs('2x gtceu:fujiazha_dust')
        .duration(40)
        .EUt(20);
event.recipes.gtceu.chemical_reactor('mcgougou:chem_fujiazha_to_rawjiasuanna_recipe')
.itemInputs('16x gtceu:fujiazha_dust')
.itemInputs('32x gtceu:sodium_hydroxide_dust')
.inputFluids( Fluid.of('water', 8000))
.outputFluids(Fluid.of("gtceu:raw_nagaoh4_solution",4000))
        .itemOutputs('2x gtceu:fujiajianjinzha_dust')
        .duration(20)
        //.circuit(1)
        .EUt(20);
event.recipes.gtceu.chemical_reactor('mcgougou:chem_rawjiasuanna_to_chunjiasn_recipe')
.inputFluids( Fluid.of('gtceu:raw_nagaoh4_solution', 4000))
.inputFluids( Fluid.of('gtceu:carbon_dioxide', 1000))
.outputFluids(Fluid.of("gtceu:nagaoh4_solution",4000))
        .itemOutputs('gtceu:sodium_bicarbonate_dust')
        .itemOutputs('gtceu:aluminum_hydroxide_dust')
        .duration(20)
        .circuit(1)
        .EUt(20);
event.recipes.gtceu.electrolyzer('mcgougou:elcetro_nagaoh4_to_ga_dust')
.inputFluids( Fluid.of('gtceu:nagaoh4_solution', 4000))
.outputFluids(Fluid.of("gtceu:oxygen",1000))
.outputFluids(Fluid.of("water",6000))
        .itemOutputs('4x gtceu:sodium_hydroxide_dust')
        .itemOutputs('4x gtceu:gallium_dust')
        .duration(20)
        .EUt(30);
event.recipes.gtceu.autoclave('mcgougou:auto_ga_as_to_gas_dust')
.itemInputs('gtceu:gallium_dust')
.itemInputs('gtceu:arsenic_dust')
        .itemOutputs('2x gtceu:gallium_arsenide_dust')
        .duration(70)
        .EUt(30);
event.recipes.gtceu.chemical_reactor('mcgougou:chem_fe_to_fecl2_recipe')
.itemInputs("gtceu:iron_dust")
.inputFluids( Fluid.of('gtceu:hydrochloric_acid', 2000))
.outputFluids(Fluid.of("gtceu:hydrogen",2000))
.outputFluids(Fluid.of("gtceu:iron_ii_chloride",1000))
        .duration(50)
        .circuit(1)
        .EUt(30);
event.recipes.gtceu.chemical_reactor('mcgougou:chem_fecl2_to_fecl3_recipe')
.inputFluids( Fluid.of('gtceu:chlorine', 1000))
.outputFluids(Fluid.of("gtceu:iron_iii_chloride",2000))
.inputFluids(Fluid.of("gtceu:iron_ii_chloride",1000))
        .duration(20)
        .EUt(30);
event.recipes.gtceu.chemical_reactor('mcgougou:chem_caoh2_to_solute_recipe')
.inputFluids( Fluid.of('water', 8000))
.itemInputs('8x gtceu:calcium_hydroxide_dust')
.outputFluids(Fluid.of("gtceu:caoh2_solution",8000))
.circuit(2)
        .duration(20)
        .EUt(30);
// event.recipes.gtceu.chemical_reactor('mcgougou:chemical_so2_to_so3')
//         .inputFluids(Fluid.of("gtceu:sulfur_dioxide",1000))
//         .notConsumable('4x gtceu:vanadium_pentoxide_dust')
//         .inputFluids(Fluid.of("gtceu:oxygen",1000))
//         .outputFluids(Fluid.of("gtceu:sulfur_trioxide",1000))
//         .duration(30)
//         .EUt(24);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_crfeo22_to_gesna')
        .itemInputs('16x gtceu:chromite_dust')
        .itemInputs('8x gtceu:soda_ash_dust')
        .itemOutputs('4x gtceu:hematite_dust')
        .itemOutputs('8x gtceu:gesuanna_dust')
        .blastFurnaceTemp(1300)
        .outputFluids(Fluid.of("gtceu:carbon_dioxide",4000))
        .duration(30)
        .circuit(1)
        .EUt(64);
event.recipes.gtceu.chemical_reactor('mcgougou:chemical_gesna_to_zgsna')
.itemInputs('8x gtceu:gesuanna_dust')
        .inputFluids(Fluid.of("gtceu:sulfuric_acid",2000))
        .itemOutputs('4x gtceu:na2so4_dust')
        .itemOutputs('4x gtceu:zhonggesuanna_dust')
        .duration(20)
        .EUt(20);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blastfurna__zgsna_to_syherge')
.itemInputs('4x gtceu:zhonggesuanna_dust')
        .itemOutputs('8x gtceu:cr2o3_dust')
.itemInputs('4x gtceu:sulfur_dust')
        .itemOutputs('4x gtceu:na2so4_dust')
        .blastFurnaceTemp(900)
        .circuit(1)
        .duration(20)
        .EUt(60);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_al_cro_to_alo_cr')
        .itemInputs('4x gtceu:cr2o3_dust')
        .itemInputs('8x gtceu:aluminium_dust')
        .itemOutputs('4x gtceu:chromium_ingot')
        .itemOutputs('20x gtceu:aluminum_oxide_dust')
        .blastFurnaceTemp(1400)
        .circuit(3)
        .duration(20)
        .EUt(50);
event.recipes.gtceu.chemical_reactor('mcgougou:chemical_cugui_to_sihcl3')
.itemInputs('gtceu:silicon_dust')
        .inputFluids(Fluid.of("gtceu:hydrochloric_acid",3000))
        .outputFluids(Fluid.of("gtceu:raw_sihcl3",1000))
        .outputFluids(Fluid.of("gtceu:hydrogen",1000))
        .circuit(1)
        .duration(20)
        .EUt(20);
event.recipes.gtceu.distillery('mcgougou:distill_rawsihcl3_to_sihcl3')
        .inputFluids(Fluid.of("gtceu:raw_sihcl3",12000))
        .outputFluids(Fluid.of("gtceu:sihcl3",10000))
        .circuit(1)
        .duration(20)
        .EUt(120);
event.recipes.gtceu.chemical_reactor('mcgougou:blast_sihcl3_to_si_and_hcl')
        .inputFluids(Fluid.of("gtceu:sihcl3",1000))
        .inputFluids(Fluid.of("gtceu:hydrogen",1000))
        .outputFluids(Fluid.of("gtceu:hydrochloric_acid",3000))
        .itemOutputs('gtceu:pure_si_dust')
        .blastFurnaceTemp(1400)
        .circuit(1)
        .duration(40)
        .EUt(120);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_puresi_to_ingot')
        .itemInputs('gtceu:pure_si_dust')
        .itemOutputs('gtceu:pure_si_ingot')
        .blastFurnaceTemp(2273)
        .circuit(1)
        .duration(159)
        .EUt(120);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_shiyingshatosi')
        .itemInputs('3x gtceu:quartz_sand_dust')
        .itemInputs('2x gtceu:carbon_dust')
        .itemOutputs('gtceu:hot_silicon_ingot').outputFluids(Fluid.of("gtceu:carbon_monoxide",2000))
        .blastFurnaceTemp(2273)
        .circuit(2)
        .duration(30)
        .EUt(120);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_linhuishi_to_gasps')
        .itemInputs('16x gtceu:apatite_dust')
        .itemInputs('15x gtceu:quartz_sand_dust')
        .itemInputs('30x gtceu:carbon_dust').outputFluids(Fluid.of("gtceu:carbon_monoxide",30000))
        .itemOutputs('9x gtceu:luzha_dust')
        .itemOutputs('6x gtceu:white_p_dust')
        .itemOutputs('gtceu:calcium_chloride_dust')
        .blastFurnaceTemp(2273)
        .duration(159)
        .EUt(120);
event.recipes.gtceu.chemical_reactor('mcgougou:chem_whitep_tpdst')
        .inputFluids(Fluid.of("gtceu:nitrogen",1000))
        .itemInputs('4x gtceu:white_p_dust')
        //.outputFluids(Fluid.of("gtceu:hydrochloric_acid",3000))
        .itemOutputs('4x gtceu:phosphorus_dust')
        .duration(25)
        .EUt(100);

event.recipes.gtceu.h2so4_factory_recipe('mcgougou:h2so4_1_recipe')
.itemInputs('8x gtceu:raw_sulfur')
        .inputFluids(Fluid.of("gtceu:oxygen",24000))
        .inputFluids(Fluid.of("water",8000))
        .outputFluids(Fluid.of("gtceu:diluted_sulfuric_acid",6000))
        .duration(640)
        .circuit(1)
        .EUt(120);
event.recipes.gtceu.h2so4_factory_recipe('mcgougou:h2so4_2_recipe')
.itemInputs('8x gtceu:raw_sulfur')
        .notConsumableFluid(Fluid.of("gtceu:sulfuric_acid",4000))
        .inputFluids(Fluid.of("gtceu:oxygen",24000))
        .inputFluids(Fluid.of("water",8000))
        .outputFluids(Fluid.of("gtceu:sulfuric_acid",8000))
        .duration(320)
        .circuit(2)
        .EUt(120);
event.recipes.gtceu.h2so4_factory_recipe('mcgougou:h2so4_3_recipe')
        .notConsumableFluid(Fluid.of("gtceu:sulfuric_acid",4000))
        .inputFluids(Fluid.of("gtceu:sulfur_dioxide",24000))
        .inputFluids(Fluid.of("gtceu:oxygen",8000))
        .inputFluids(Fluid.of("water",8000))
        .outputFluids(Fluid.of("gtceu:sulfuric_acid",8000))
        .duration(270)
        .circuit(3)
        .EUt(120);
event.recipes.gtceu.compressor('mcgougou:press_shiomotoblovks')
        .itemInputs('9x gtceu:graphite_dust')
        .itemOutputs('mcgougou:shimo')
        .duration(20)
        .EUt(100);
event.recipes.gtceu.plastic_recipe('mcgougou:plastic_c2h4')
        .inputFluids( Fluid.of('gtceu:ethylene', 144000))
        .inputFluids(Fluid.of("gtceu:oxygen",1))
        .outputFluids(Fluid.of('gtceu:polyethylene', 136800))
        .circuit(1)
        .duration(600)
        .EUt(120);
event.recipes.gtceu.centrifuge('mcgougou:cent_graphshenmg')
.itemInputs('gtceu:graphite_dust')
.itemOutputs('4x gtceu:carbon_dust')
        .duration(10)
        .EUt(60);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_sb')
.itemInputs('5x gtceu:antimony_trioxide_dust')
.itemInputs('3x gtceu:carbon_dust')
.itemOutputs('2x gtceu:antimony_dust')
        .outputFluids(Fluid.of('gtceu:carbon_monoxide', 3000))
        .circuit(1)
        .blastFurnaceTemp(1200)
        .duration(40)
        .EUt(120);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_pb')
.itemInputs('2x gtceu:massicot_dust')
.itemInputs('gtceu:carbon_dust')
.itemOutputs('gtceu:lead_ingot')
        .outputFluids(Fluid.of('gtceu:carbon_monoxide', 1000))
        .circuit(1)
        .blastFurnaceTemp(1100)
        .duration(20)
        .EUt(120);
event.recipes.gtceu.chemical_reactor('mcgougou:chem_chem_mgo_to_solute')
.itemInputs('gtceu:magnesia_dust')
        .inputFluids( Fluid.of('gtceu:hydrochloric_acid', 2000))
        .outputFluids(Fluid.of("gtceu:mgcl2_solution",2000))
        .duration(20)
        .circuit(1)
        .EUt(60);
event.recipes.gtceu.chemical_reactor('mcgougou:chemmgcl2_to_jiejing')
        .inputFluids(Fluid.of("gtceu:mgcl2_solution",1000))
        .inputFluids( Fluid.of('gtceu:hydrochloric_acid', 2000))
        .outputFluids(Fluid.of("gtceu:diluted_hydrochloric_acid",2000))
        .itemOutputs('gtceu:magnesium_chloride_dust')
        .duration(20)
        .circuit(1)
        .EUt(60);
event.recipes.gtceu.extractor('mcgougou:tiqu_mgcl2')
        .itemInputs('gtceu:magnesium_chloride_dust')
        .outputFluids(Fluid.of("gtceu:mgcl2_molten",144))
        .duration(4)
        .EUt(120);
event.recipes.gtceu.extractor('mcgougou:tiqu_nacl')
        .itemInputs('gtceu:salt_dust')
        .outputFluids(Fluid.of("gtceu:nacl_molten",144))
        .duration(4)
        .EUt(120);
event.recipes.gtceu.electrolyzer('mcgougou:elceto_nacl')
        .inputFluids(Fluid.of("gtceu:nacl_molten",288))
        .outputFluids(Fluid.of("gtceu:chlorine",1000))
        .itemOutputs('gtceu:sodium_dust')
        .duration(32)
        .EUt(120);
event.recipes.gtceu.electrolyzer('mcgougou:elceto_mgcl2')
        .inputFluids(Fluid.of("gtceu:mgcl2_molten",432))
        .outputFluids(Fluid.of("gtceu:chlorine",2000))
        .itemOutputs('gtceu:magnesium_dust')
        .duration(25)
        .EUt(120);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_kcl_na_to_nacl_k')
        .itemInputs('gtceu:rock_salt_dust')
        .itemInputs('gtceu:sodium_dust')
        .outputFluids(Fluid.of("gtceu:k_gas",1000))
        .itemOutputs('gtceu:salt_dust')
        .blastFurnaceTemp(1123)
        .duration(40)
        .EUt(240);
event.recipes.gtceu.fluid_solidifier('mcgougou:lengque_k_gas')
        .inputFluids(Fluid.of("gtceu:k_gas",1000))
        .itemOutputs('gtceu:potassium_dust')
        .duration(20)
        .EUt(120);
event.recipes.gtceu.hv_generator_recipe('mcgougou:hv_generator_1')
        .inputFluids(Fluid.of('gtceu:natural_gas', 1000))
        .inputFluids( Fluid.of('gtceu:oxygen', 3000))
        .inputFluids( Fluid.of('water', 400))
        .outputFluids(Fluid.of('gtceu:distilled_water', 300))
        .duration(50)
        .circuit(1)
        .EUt(-32768);
event.recipes.gtceu.hv_generator_recipe('mcgougou:hv_generator_11')
        .inputFluids(Fluid.of('gtceu:methane', 1000))
        .inputFluids( Fluid.of('gtceu:oxygen', 3000))
        .inputFluids( Fluid.of('water', 400))
        .outputFluids(Fluid.of('gtceu:distilled_water', 300))
        .duration(75)
        .circuit(1)
        .EUt(-32768);
event.recipes.gtceu.hv_generator_recipe('mcgougou:hv_generator_2')
.itemInputs('2x gtceu:anthracite_coal_dust')
        .inputFluids( Fluid.of('gtceu:oxygen', 4000))
        .inputFluids( Fluid.of('water', 400))
        .itemOutputs('gtceu:tiny_ash_dust')
        .outputFluids(Fluid.of('gtceu:distilled_water', 300))
        .duration(90)
        .circuit(2)
        .EUt(-8192);
event.recipes.gtceu.chemical_reactor('mcgougou:chem_caf2_to_hf_acid')
        .inputFluids(Fluid.of("gtceu:sulfuric_acid",1000))
        .itemInputs('2x gtceu:caf2_dust')
        .outputFluids(Fluid.of("gtceu:hydrofluoric_acid",2000))
        .duration(20)
        .circuit(1)
        .EUt(200);
event.recipes.gtceu.chemical_reactor('mcgougou:chem_ch4_to_cxhxclx_mix')
        .inputFluids(Fluid.of("gtceu:methane",8000))
        .inputFluids(Fluid.of("gtceu:chlorine",4000))
        .outputFluids(Fluid.of("gtceu:hydrochloric_acid",1000))
        .outputFluids(Fluid.of("gtceu:chxclx_mix",3000))
        .duration(20)
        .circuit(1)
        .EUt(400);
event.recipes.gtceu.distillation_tower('mcgougou:distilll_cxhxclx_mix')
        .inputFluids(Fluid.of("gtceu:chxclx_mix",1000)).outputFluids(Fluid.of("gtceu:chloromethane",320)).outputFluids(Fluid.of("gtceu:ch2cl2",280))
        .outputFluids(Fluid.of("gtceu:chloroform",240)).disableDistilleryRecipes(true)
        .outputFluids(Fluid.of("gtceu:ccl4",160))
        .duration(60)
        .EUt(400);
event.recipes.gtceu.chemical_reactor('mcgougou:chem_sb_to_sbcl5')
        .inputFluids(Fluid.of("gtceu:chlorine",5000))
        .itemInputs('gtceu:antimony_dust')
        .outputFluids(Fluid.of("gtceu:sbcl5",1000))
        .duration(20)
        .circuit(1)
        .EUt(400);
event.recipes.gtceu.chemical_reactor('mcgougou:chem_hf_lvfang_to_r22')
        .inputFluids(Fluid.of("gtceu:hydrofluoric_acid",1000))
        .inputFluids(Fluid.of("gtceu:chloroform",1000))
        .notConsumableFluid(Fluid.of("gtceu:sbcl5",1000))
        .outputFluids(Fluid.of("gtceu:chclf2",1000))
        .outputFluids(Fluid.of("gtceu:hydrochloric_acid",1000))
        .duration(20)
        .circuit(1)
        .EUt(400);
event.recipes.gtceu.cracker('mcgougou:crack_r22_steam')
        .inputFluids(Fluid.of("gtceu:chclf2",1000))
        .inputFluids(Fluid.of("gtceu:steam",1000))
        .outputFluids(Fluid.of("gtceu:h2o_chclf2",1000))
        .duration(10)
        .circuit(10)
        .EUt(400);
event.recipes.gtceu.distillation_tower('mcgougou:distilll_h2o_chclf2')
        .inputFluids(Fluid.of("gtceu:h2o_chclf2",1000))
        .outputFluids(Fluid.of("gtceu:steam",900)).outputFluids(Fluid.of("gtceu:tetrafluoroethylene",500))
        .outputFluids(Fluid.of("gtceu:chclf2",200))
        .duration(60).disableDistilleryRecipes(true)
        .EUt(400);
event.recipes.gtceu.chemical_reactor('mcgougou:chem_nh4_h2so4_to_nh4hso4')
        .inputFluids(Fluid.of("gtceu:ammonia",1000))
        .inputFluids(Fluid.of("gtceu:sulfuric_acid",1000))
        .outputFluids(Fluid.of("gtceu:nh4hso4",1000))
        .duration(20)
        .circuit(1)
        .EUt(100);
event.recipes.gtceu.electrolyzer('mcgougou:elec_nahso4')
.itemInputs('2x gtceu:sodium_bisulfate_dust')
        .inputFluids(Fluid.of("gtceu:distilled_water",1000))
        .outputFluids(Fluid.of("gtceu:sodium_persulfate",1000))
        .outputFluids(Fluid.of("gtceu:hydrogen",1000))
        .duration(40)
        .circuit(1)
        .EUt(100);
event.recipes.gtceu.electrolyzer('mcgougou:elec_nh4hso4')
        .inputFluids(Fluid.of("gtceu:nh4hso4",2000))
        .outputFluids(Fluid.of("gtceu:nh42s2o8",1000))
        .outputFluids(Fluid.of("gtceu:hydrogen",1000))
        .duration(40)
        .circuit(1)
        .EUt(100);

event.recipes.gtceu.plastic_recipe('mcgougou:plastic_c2f4')
        .inputFluids( Fluid.of('gtceu:tetrafluoroethylene', 144000))
        .inputFluids(Fluid.of("gtceu:nh42s2o8",20))
        .outputFluids(Fluid.of('gtceu:polytetrafluoroethylene', 136800))
        .circuit(2)
        .duration(600)
        .EUt(500);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_dihcishdu')
        .inputFluids( Fluid.of('gtceu:dichloroethane', 1000))
        .outputFluids(Fluid.of('gtceu:vinyl_chloride', 900))
        .blastFurnaceTemp(720)
        .circuit(1)
        .duration(10)
        .EUt(500);
        
event.recipes.gtceu.plastic_recipe('mcgougou:plastic_pvc')
        .inputFluids( Fluid.of('gtceu:vinyl_chloride', 144000))
        .inputFluids(Fluid.of("gtceu:nh42s2o8",20))
        .outputFluids(Fluid.of('gtceu:polyvinyl_chloride', 136800))
        .circuit(3)
        .duration(600)
        .EUt(500);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_1_rocket_mat')
        .inputFluids( Fluid.of('gtceu:soldering_alloy', 1440))
        .itemInputs('32x gtceu:stainless_steel_ingot')
        .itemInputs('64x gtceu:wrought_iron_ingot')
        .itemOutputs('gtceu:rocket_1_material_block')
        .blastFurnaceTemp(3600)
        .circuit(11)
        .duration(150)
        .EUt(1024);
event.recipes.gtceu.assembler('mcgougou:ass_1_rock_eng')
        .itemInputs('2x ad_astra:steel_tank')
        .itemInputs('7x gtceu:dense_rocket_1_material_plate')
        .itemInputs('4x gtceu:rocket_1_material_gear')
        .itemInputs('2x gtceu:rocket_1_material_spring')
        .itemInputs('16x gtceu:rocket_1_material_screw')
        .itemInputs('gtceu:long_rocket_1_material_rod')
        .inputFluids( Fluid.of('gtceu:soldering_alloy', 1440))
        .itemOutputs('ad_astra:steel_engine')
        .circuit(11)
        .duration(150)
        .EUt(1024);
event.recipes.gtceu.vacuum_freezer('mcgougou:freeeeeza_ch4')
        .inputFluids( Fluid.of('gtceu:methane', 1000)).outputFluids(Fluid.of('gtceu:ch4_l', 1000))
        
        .duration(20)
        .EUt(1920);
event.recipes.gtceu.distillation_tower('mcgougou:dist_ch4_liquid').inputFluids(Fluid.of('gtceu:ch4_l', 1000))
       .outputFluids(Fluid.of('gtceu:methane', 750))
       .chancedFluidOutput(Fluid.of('gtceu:pure_ch4', 100),800,0)
        .duration(40)
        .EUt(1920);
event.recipes.gtceu.vacuum_freezer('mcgougou:freeeeeza_pure__ch4')
        .inputFluids( Fluid.of('gtceu:pure_ch4', 1000)).outputFluids(Fluid.of('gtceu:pure_ch4_l', 1000))
        
        .duration(20)
        .EUt(1920);
event.recipes.gtceu.mixer('mcgougou:mix_1_eo_fuel')
        .inputFluids(Fluid.of('gtceu:pure_ch4_l', 1000))
        .inputFluids(Fluid.of('gtceu:liquid_oxygen', 2000))
        .outputFluids(Fluid.of('gtceu:tier1_rocket_fuel', 1000))
        .duration(30)
        .EUt(1024);
event.recipes.gtceu.assembler('mcgougou:ass_moon_marker')
        .itemInputs('gtceu:overworld_marker')
        .itemInputs('ad_astra:moon_stone')
        .itemOutputs('mcgougou:moon_marker')
        .circuit(11)
        .dimension("ad_astra:moon")
        .duration(300)
        .EUt(2048);
event.recipes.gtceu.distillation_tower('mcgougou:dist_ticl44444')
.disableDistilleryRecipes(true)
.inputFluids( Fluid.of('gtceu:raw_ticl4', 12000))
.outputFluids( Fluid.of('gtceu:titanium_tetrachloride', 10000))
        .duration(15)
        .EUt(1920);
event.recipes.gtceu.vacuum_freezer('mcgougou:vac_nether_stone')
.inputFluids( Fluid.of('minecraft:lava', 12000))
.itemInputs('minecraft:redstone')
.itemOutputs('minecraft:netherrack')
        .duration(10)
        .EUt(1920);
event.recipes.gtceu.assembler('mcgougou:ass_nethermark')
.itemInputs('gtceu:overworld_marker')
.itemInputs('64x minecraft:netherrack')
.itemOutputs('gtceu:the_nether_marker')
.circuit(10)
        .duration(300)
        .EUt(1920);

event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_boxi_cl_2')
.itemInputs('8x gtceu:platinum_group_sludge_dust').inputFluids( Fluid.of('gtceu:chlorine', 1000))
.inputFluids( Fluid.of('gtceu:hydrochloric_acid', 1000)).outputFluids(Fluid.of("gtceu:boxi_cl",1000))
        .duration(20)
        .itemOutputs('gtceu:platinum_sludge_residue_dust')
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_boxi_ru_os_out')
.inputFluids( Fluid.of('gtceu:chlorine', 1000))
.inputFluids(Fluid.of("gtceu:boxi_cl",1000))
.outputFluids(Fluid.of("gtceu:boxi_cl_out_ruos",700))
.outputFluids(Fluid.of("gtceu:ruoso4_gas",300))
        .duration(20)
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_ru_os_fenli')
.inputFluids(Fluid.of("gtceu:ruoso4_gas",1000))
.inputFluids(Fluid.of("gtceu:diluted_hydrochloric_acid",1000))
.itemOutputs('gtceu:osmium_tetroxide_dust')
.outputFluids(Fluid.of("gtceu:hrucl",500))
        .duration(20)
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_oso4_to_ossuan')
.itemInputs('gtceu:osmium_tetroxide_dust')
.itemInputs('2x gtceu:sodium_hydroxide_dust')
.outputFluids(Fluid.of("gtceu:na2oso4",500))
        .duration(20)
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_ossuanna_to_ossuan')
.inputFluids(Fluid.of("gtceu:na2oso4",1000)).inputFluids( Fluid.of('gtceu:hydrochloric_acid', 1000))
.outputFluids(Fluid.of("gtceu:hoscl",1000))
        .duration(20)
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_ossuan_chendian')
.itemInputs('2x gtceu:ammonium_chloride_dust')
.inputFluids(Fluid.of("gtceu:hoscl",1000))
.itemOutputs('gtceu:nh4os_dust')
        .duration(20)
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_rusuan_chendian')
.itemInputs('2x gtceu:ammonium_chloride_dust')
.inputFluids(Fluid.of("gtceu:hrucl",1000))
.itemOutputs('gtceu:nh4ru_dust')
        .duration(20)
        .EUt(1920);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_rusuan')
.inputFluids(Fluid.of("gtceu:nitrogen",100))
.itemInputs('gtceu:nh4ru_dust')
.itemOutputs('gtceu:ruthenium_dust')
.blastFurnaceTemp(873)
        .duration(20)
        .EUt(1920);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_ossuan')
.inputFluids(Fluid.of("gtceu:nitrogen",100))
.itemInputs('gtceu:nh4os_dust')
.itemOutputs('gtceu:osmium_dust')
.blastFurnaceTemp(873)
        .duration(20)
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_pd_out')
.inputFluids( Fluid.of('gtceu:ammonia', 500))
.inputFluids(Fluid.of("gtceu:boxi_cl_out_ruos",1000))
.itemOutputs('gtceu:small_pdoh_dust')
.outputFluids(Fluid.of("gtceu:boxi_cl_out_3",750))
        .duration(20)
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_pd_erlveran')
.inputFluids( Fluid.of('gtceu:ammonia', 2000)).inputFluids( Fluid.of('gtceu:hydrochloric_acid', 1000))
.itemInputs('gtceu:pdoh_dust')
.itemOutputs('gtceu:pdnh3cl_dust')
        .duration(20)
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_btld')
.inputFluids( Fluid.of('gtceu:ammonia', 4000))
.inputFluids( Fluid.of('gtceu:chlorine', 1000))
.itemOutputs('2x gtceu:ammonium_chloride_dust')
.outputFluids(Fluid.of("water",2000))
.inputFluids( Fluid.of('gtceu:acetone', 2000))
.outputFluids(Fluid.of("gtceu:bingtongliandan",1000))
.circuit(11)
        .duration(20)
        .EUt(1920);
event.recipes.gtceu.plastic_recipe('mcgougou:pla_n2h4')
.inputFluids(Fluid.of("water",20000))
.outputFluids( Fluid.of('gtceu:acetone', 20000))
.outputFluids( Fluid.of('gtceu:n2h4h2o', 9000))
.inputFluids(Fluid.of("gtceu:bingtongliandan",10000))
.circuit(0)
        .duration(200)
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_pd_dddddd')
.inputFluids( Fluid.of('gtceu:n2h4h2o', 1000))
.itemInputs('gtceu:pdnh3cl_dust')
.itemOutputs('gtceu:palladium_dust')
.itemOutputs('2x gtceu:ammonium_chloride_dust')
        .duration(20)
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_ptsuan_chendian')
.itemInputs('2x gtceu:ammonium_chloride_dust')
.inputFluids(Fluid.of("gtceu:boxi_cl_out_3",1000))
.itemOutputs('2x gtceu:small_nh4pt_dust')
.outputFluids(Fluid.of("gtceu:boxi_cl_out_4",600))
        .duration(20)
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_fenliir')
.itemInputs('2x gtceu:ammonium_chloride_dust')
.inputFluids(Fluid.of("gtceu:chlorine",500))
.inputFluids(Fluid.of("gtceu:boxi_cl_out_4",1000))
.outputFluids(Fluid.of("gtceu:hrhcl",500))
.itemOutputs('2x gtceu:small_nh4ir_dust')
        .duration(20)
        .EUt(1920);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_ptsuan')
.inputFluids(Fluid.of("gtceu:nitrogen",100))
.itemInputs('gtceu:nh4pt_dust')
.itemOutputs('gtceu:platinum_dust')
.blastFurnaceTemp(873)
        .duration(20)
        .EUt(1920);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_irsuan')
.inputFluids(Fluid.of("gtceu:nitrogen",100))
.itemInputs('gtceu:nh4ir_dust')
.itemOutputs('gtceu:iridium_dust')
.blastFurnaceTemp(873)
        .duration(20)
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_rhsuann')
.itemInputs('2x gtceu:ammonium_chloride_dust')
.inputFluids(Fluid.of("gtceu:hrhcl",1000))
.itemOutputs('gtceu:nh4rh_dust')
        .duration(20)
        .EUt(1920);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_rhsuan')
.inputFluids(Fluid.of("gtceu:nitrogen",100))
.itemInputs('gtceu:nh4rh_dust')
.itemOutputs('gtceu:rhodium_dust')
.blastFurnaceTemp(873)
        .duration(20)
        .EUt(1920);
event.recipes.gtceu.electrolyzer('mcgougou:electro_watttttter')
.inputFluids(Fluid.of("water",1000)).outputFluids(Fluid.of("gtceu:hydrogen",2000)).outputFluids(Fluid.of("gtceu:oxygen",1000))
.circuit(0)
        .duration(240000)
        .EUt(30);
event.recipes.gtceu.chemical_reactor('mcgougou:chem_caohwwwww2')
.inputFluids(Fluid.of("water",1000))
.itemInputs('2x gtceu:quicklime_dust')
.itemOutputs('3x gtceu:calcium_hydroxide_dust')
.circuit(0)
        .duration(10)
        .EUt(30);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_bugfix112211')
.itemInputs('gtceu:kanthal_dust')
.itemOutputs('gtceu:hot_kanthal_ingot')
.blastFurnaceTemp(1800)
.circuit(1)
        .duration(90)
        .EUt(120);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_bugfix1111')
.inputFluids(Fluid.of("gtceu:nitrogen",1000))
.itemInputs('gtceu:kanthal_dust')
.itemOutputs('gtceu:hot_kanthal_ingot')
.blastFurnaceTemp(1800)
.circuit(2)
        .duration(60)
        .EUt(120);
event.recipes.gtceu.hno3_recipe('mcgougou:hno3_01')
.inputFluids(Fluid.of("gtceu:ammonia",10000))
.inputFluids(Fluid.of("gtceu:air",90000))
.inputFluids(Fluid.of("water",10000)).outputFluids(Fluid.of("gtceu:nitric_acid",5700))
.circuit(1)
        .duration(500)
        .EUt(1920);
event.recipes.gtceu.hno3_recipe('mcgougou:hno3_02')
.inputFluids(Fluid.of("gtceu:ammonia",10000))
.inputFluids(Fluid.of("gtceu:air",90000))
.inputFluids(Fluid.of("water",10000)).outputFluids(Fluid.of("gtceu:nitric_acid",8151))
.circuit(2)
        .duration(1000)
        .EUt(1920);
event.recipes.gtceu.hno3_recipe('mcgougou:hno3_03')
.inputFluids(Fluid.of("gtceu:ammonia",10000))
.inputFluids(Fluid.of("gtceu:air",90000))
.inputFluids(Fluid.of("water",10000)).outputFluids(Fluid.of("gtceu:nitric_acid",9205))
.circuit(3)
        .duration(1500)
        .EUt(1920);
event.recipes.gtceu.hno3_recipe('mcgougou:hno3_11')
.inputFluids(Fluid.of("gtceu:ammonia",10000))
.inputFluids(Fluid.of("gtceu:air",90000)).outputFluids(Fluid.of("gtceu:nitrogen_dioxide",6000))
.circuit(11)
        .duration(300)
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_pcl3')
.itemInputs('gtceu:white_p_dust')
.inputFluids(Fluid.of("gtceu:chlorine",3000))
.outputFluids(Fluid.of("gtceu:pcl3",1000))
        .duration(10)
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_xxquan')
.notConsumable('gtceu:sodium_hydroxide_dust')
.inputFluids(Fluid.of("gtceu:butyraldehyde",2500))
.outputFluids(Fluid.of("gtceu:xinxiquan",1000))
        .duration(30)
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_yxchunnn')
.notConsumable('gtceu:copper_dust')
.inputFluids(Fluid.of("gtceu:hydrogen",2000))
.inputFluids(Fluid.of("gtceu:xinxiquan",1000))
.outputFluids(Fluid.of("gtceu:yixinchun",1000))
        .duration(40)
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_zncl')
.itemInputs('gtceu:zinc_dust')
.inputFluids(Fluid.of("gtceu:hydrochloric_acid",2000)).outputFluids(Fluid.of("gtceu:hydrogen",1000))
.itemOutputs('gtceu:zncl2_dust')
        .duration(20)
        .EUt(120);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_yxccl_11561')
.inputFluids(Fluid.of("gtceu:hydrochloric_acid",1000)).inputFluids(Fluid.of("gtceu:yixinchun",1000)).outputFluids(Fluid.of("gtceu:lvdaiyixinwan",1000))
.notConsumable('gtceu:zncl2_dust')
        .duration(30)
        .EUt(1920);

event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_yichunnaaa')
.inputFluids(Fluid.of("gtceu:ethanol",1000)).outputFluids(Fluid.of("gtceu:hydrogen",1000))
.itemInputs('gtceu:sodium_dust')
.itemOutputs('gtceu:yichunna_dust')
        .duration(10)
        .EUt(500);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_yalinsuanshenmegui')
.inputFluids(Fluid.of("gtceu:yixinchun",3000)).inputFluids(Fluid.of("gtceu:pcl3",1000)).outputFluids(Fluid.of("gtceu:lvdaiyixinwan",1000))
.outputFluids(Fluid.of("gtceu:hydrochloric_acid",2000))
.outputFluids(Fluid.of("gtceu:yalinsuaneryixingxinzhi",1000))
        .duration(30)
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_yaanana')
.itemInputs('gtceu:yichunna_dust').outputFluids(Fluid.of("gtceu:ethanol",1000))
.outputFluids(Fluid.of("gtceu:yalinsuaneryixingxinzhina",1000))
.inputFluids(Fluid.of("gtceu:yalinsuaneryixingxinzhi",1000))
        .duration(30)
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_yaanana_plus_rcl')
.outputFluids(Fluid.of("gtceu:linsuaneryixingxinzhi",1000))
.itemOutputs('gtceu:salt_dust')
.inputFluids(Fluid.of("gtceu:yalinsuaneryixingxinzhina",1000))
.inputFluids(Fluid.of("gtceu:lvdaiyixinwan",1000))
        .duration(30)
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_08021645')
.inputFluids(Fluid.of("gtceu:linsuaneryixingxinzhi",1000))
.itemInputs('gtceu:sodium_hydroxide_dust').outputFluids(Fluid.of("gtceu:p507nayan",1000)).outputFluids(Fluid.of("gtceu:yixinchun",900))
        .duration(30)
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_08021646')
.inputFluids(Fluid.of("gtceu:p507nayan",1000)).inputFluids(Fluid.of("gtceu:hydrochloric_acid",1000))
.outputFluids(Fluid.of("gtceu:p507",1000)).itemOutputs('gtceu:salt_dust')
        .duration(30)
        .EUt(1920);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_xitusso4')
.inputFluids(Fluid.of("gtceu:sulfuric_acid",24000))
.itemInputs('16x gtceu:rare_earth_dust')
.itemOutputs('16x gtceu:re2so43_dust')
.blastFurnaceTemp(800)
        .duration(80)
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_xituoh3')
.itemInputs('16x gtceu:re2so43_dust')
.itemInputs('48x gtceu:sodium_hydroxide_dust')
.itemOutputs('16x gtceu:reoh3_dust')
.itemOutputs('24x gtceu:na2so4_dust')
        .duration(80)
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_xitucl3')
.inputFluids(Fluid.of("gtceu:hydrochloric_acid",48000))
.itemInputs('16x gtceu:reoh3_dust')
.outputFluids(Fluid.of("gtceu:recl3",16000))
        .duration(80)
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_hhmy')
.inputFluids(Fluid.of("gtceu:sulfuric_acid",1000))
.inputFluids(Fluid.of("gtceu:naphtha",5000))
.outputFluids(Fluid.of("gtceu:hhmy",6000))
        .duration(20)
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_yisuanyixz')
.notConsumable('gtceu:palladium_dust')
.inputFluids(Fluid.of("gtceu:acetic_acid",1000))
.inputFluids(Fluid.of("gtceu:ethylene",1000))
.inputFluids(Fluid.of("gtceu:oxygen",500))
.outputFluids(Fluid.of("gtceu:vinyl_acetate",1000))
.outputFluids(Fluid.of("water",1000))
.circuit(3)
        .duration(20)
        .EUt(1920);
event.recipes.gtceu.plastic_recipe('mcgougou:plastic_ysyxz')
        .inputFluids( Fluid.of("gtceu:vinyl_acetate", 144000))
        .inputFluids(Fluid.of("gtceu:nh42s2o8",1))
        .outputFluids(Fluid.of('gtceu:polyvinyl_acetate', 136800))
        .circuit(4)
        .duration(600)
        .EUt(1920);
event.recipes.gtceu.plastic_recipe('mcgougou:plastic_pvb')
.notConsumableFluid(Fluid.of("gtceu:hydrochloric_acid",12000))
        .inputFluids(Fluid.of("gtceu:methanol",1000000))
        .inputFluids(Fluid.of('gtceu:polyvinyl_acetate', 100000))
        .inputFluids(Fluid.of('gtceu:butyraldehyde', 70000))
        .outputFluids(Fluid.of("gtceu:methanol",900000))
        .outputFluids(Fluid.of("gtceu:polyvinyl_butyral",90000))
        .circuit(5)
        .duration(600)
        .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_dingquan')
.notConsumable('gtceu:rhodium_dust')
.inputFluids(Fluid.of("gtceu:hydrogen",2000))
.inputFluids(Fluid.of("gtceu:carbon_monoxide",1000))
.inputFluids(Fluid.of("gtceu:propene",1000))
.outputFluids(Fluid.of("gtceu:butyraldehyde",1000))
        .duration(20)
        .EUt(1920);
event.recipes.gtceu.xitu_recipe('mcgougou:xitu_1')
.outputFluids(Fluid.of("gtceu:sccl3",625))
.outputFluids(Fluid.of("gtceu:lacl3",625))
.outputFluids(Fluid.of("gtceu:cecl3",625))
.outputFluids(Fluid.of("gtceu:prcl3",625))
.outputFluids(Fluid.of("gtceu:ndcl3",625))
.outputFluids(Fluid.of("gtceu:smcl3",625))
.outputFluids(Fluid.of("gtceu:eucl3",625))
.outputFluids(Fluid.of("gtceu:gdcl3",625))
.outputFluids(Fluid.of("gtceu:tbcl3",625))
.outputFluids(Fluid.of("gtceu:dycl3",625))
.outputFluids(Fluid.of("gtceu:hocl3",625))
.outputFluids(Fluid.of("gtceu:ercl3",625))
.outputFluids(Fluid.of("gtceu:tmcl3",625))
.outputFluids(Fluid.of("gtceu:ybcl3",625))
.outputFluids(Fluid.of("gtceu:lucl3",625))
.outputFluids(Fluid.of("gtceu:ycl3",625))
.inputFluids(Fluid.of("gtceu:recl3",12000))
.inputFluids(Fluid.of("gtceu:ammonia",1200))
.inputFluids(Fluid.of("gtceu:hydrochloric_acid",14400))
.notConsumableFluid(Fluid.of("gtceu:ammonia",12000))
.notConsumableFluid(Fluid.of("gtceu:hhmy",216000))
.notConsumableFluid(Fluid.of("gtceu:p507",72000))
.notConsumableFluid(Fluid.of("gtceu:hydrochloric_acid",480000))
        .duration(250)
        .EUt(1920);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_bi')
.itemInputs('gtceu:bi2o3_dust')
.itemInputs('3x gtceu:carbon_dust')
.itemOutputs('2x gtceu:bismuth_dust')
.outputFluids(Fluid.of("gtceu:carbon_monoxide",3000))
.blastFurnaceTemp(1073)
        .duration(20)
        .EUt(120);
event.recipes.gtceu.ev_generator_recipe('mcgougou:ev_generator_1')
        .inputFluids(Fluid.of('gtceu:oil_heavy', 10000))
        .inputFluids( Fluid.of('water', 1000000))
        .outputFluids(Fluid.of('gtceu:distilled_water', 750000))
        .itemOutputs('64x gtceu:dark_ash_dust')
        .duration(20)
        .circuit(1)
        .EUt(-2097152);
// event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_laco3')
// .inputFluids( Fluid.of('gtceu:lacl3', 2000))
// .itemInputs('3x gtceu:soda_ash_dust')
// .itemOutputs('gtceu:laco3_dust')
// .outputFluids(Fluid.of("gtceu:salt_water",3000))
//         .duration(10)
//         .EUt(1920);
event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_scco3')
.inputFluids( Fluid.of('gtceu:sccl3', 2000))
.itemInputs('3x gtceu:soda_ash_dust')
.itemOutputs('gtceu:scco3_dust')
.outputFluids(Fluid.of("gtceu:salt_water",3000))
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_laco3')
.inputFluids( Fluid.of('gtceu:lacl3', 2000))
.itemInputs('3x gtceu:soda_ash_dust')
.itemOutputs('gtceu:laco3_dust')
.outputFluids(Fluid.of("gtceu:salt_water",3000))
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_ceco3')
.inputFluids( Fluid.of('gtceu:cecl3', 2000))
.itemInputs('3x gtceu:soda_ash_dust')
.itemOutputs('gtceu:ceco3_dust')
.outputFluids(Fluid.of("gtceu:salt_water",3000))
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_prco3')
.inputFluids( Fluid.of('gtceu:prcl3', 2000))
.itemInputs('3x gtceu:soda_ash_dust')
.itemOutputs('gtceu:prco3_dust')
.outputFluids(Fluid.of("gtceu:salt_water",3000))
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_ndco3')
.inputFluids( Fluid.of('gtceu:ndcl3', 2000))
.itemInputs('3x gtceu:soda_ash_dust')
.itemOutputs('gtceu:ndco3_dust')
.outputFluids(Fluid.of("gtceu:salt_water",3000))
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_smco3')
.inputFluids( Fluid.of('gtceu:smcl3', 2000))
.itemInputs('3x gtceu:soda_ash_dust')
.itemOutputs('gtceu:smco3_dust')
.outputFluids(Fluid.of("gtceu:salt_water",3000))
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_eucl3')
.inputFluids( Fluid.of('gtceu:eucl3', 2000))
.itemInputs('3x gtceu:soda_ash_dust')
.itemOutputs('gtceu:euco3_dust')
.outputFluids(Fluid.of("gtceu:salt_water",3000))
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_gdco3')
.inputFluids( Fluid.of('gtceu:gdcl3', 2000))
.itemInputs('3x gtceu:soda_ash_dust')
.itemOutputs('gtceu:gdco3_dust')
.outputFluids(Fluid.of("gtceu:salt_water",3000))
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_tbco3')
.inputFluids( Fluid.of('gtceu:tbcl3', 2000))
.itemInputs('3x gtceu:soda_ash_dust')
.itemOutputs('gtceu:tbco3_dust')
.outputFluids(Fluid.of("gtceu:salt_water",3000))
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_dyco3')
.inputFluids( Fluid.of('gtceu:dycl3', 2000))
.itemInputs('3x gtceu:soda_ash_dust')
.itemOutputs('gtceu:dyco3_dust')
.outputFluids(Fluid.of("gtceu:salt_water",3000))
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_hoco3')
.inputFluids( Fluid.of('gtceu:hocl3', 2000))
.itemInputs('3x gtceu:soda_ash_dust')
.itemOutputs('gtceu:hoco3_dust')
.outputFluids(Fluid.of("gtceu:salt_water",3000))
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_erco3')
.inputFluids( Fluid.of('gtceu:ercl3', 2000))
.itemInputs('3x gtceu:soda_ash_dust')
.itemOutputs('gtceu:erco3_dust')
.outputFluids(Fluid.of("gtceu:salt_water",3000))
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_tmco3')
.inputFluids( Fluid.of('gtceu:tmcl3', 2000))
.itemInputs('3x gtceu:soda_ash_dust')
.itemOutputs('gtceu:tmco3_dust')
.outputFluids(Fluid.of("gtceu:salt_water",3000))
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_ybco3')
.inputFluids( Fluid.of('gtceu:ybcl3', 2000))
.itemInputs('3x gtceu:soda_ash_dust')
.itemOutputs('gtceu:ybco3_dust')
.outputFluids(Fluid.of("gtceu:salt_water",3000))
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_luco3')
.inputFluids( Fluid.of('gtceu:lucl3', 2000))
.itemInputs('3x gtceu:soda_ash_dust')
.itemOutputs('gtceu:luco3_dust')
.outputFluids(Fluid.of("gtceu:salt_water",3000))
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.large_chemical_reactor('mcgougou:chem_yco3')
.inputFluids( Fluid.of('gtceu:ycl3', 2000))
.itemInputs('3x gtceu:soda_ash_dust')
.itemOutputs('gtceu:yco3_dust')
.outputFluids(Fluid.of("gtceu:salt_water",3000))
        .duration(10)
        .EUt(1920);event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_sc2o3')
.itemInputs('gtceu:scco3_dust')
.itemOutputs('gtceu:sc2o3_dust')
.outputFluids(Fluid.of("gtceu:carbon_dioxide",3000))
.blastFurnaceTemp(1173)
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_la2o3')
.itemInputs('gtceu:laco3_dust')
.itemOutputs('gtceu:la2o3_dust')
.outputFluids(Fluid.of("gtceu:carbon_dioxide",3000))
.blastFurnaceTemp(1173)
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_ce2o3')
.itemInputs('gtceu:ceco3_dust')
.itemOutputs('gtceu:ce2o3_dust')
.outputFluids(Fluid.of("gtceu:carbon_dioxide",3000))
.blastFurnaceTemp(1173)
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_pr2o3')
.itemInputs('gtceu:prco3_dust')
.itemOutputs('gtceu:pr2o3_dust')
.outputFluids(Fluid.of("gtceu:carbon_dioxide",3000))
.blastFurnaceTemp(1173)
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_nd2o3')
.itemInputs('gtceu:ndco3_dust')
.itemOutputs('gtceu:nd2o3_dust')
.outputFluids(Fluid.of("gtceu:carbon_dioxide",3000))
.blastFurnaceTemp(1173)
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_sm2o3')
.itemInputs('gtceu:smco3_dust')
.itemOutputs('gtceu:sm2o3_dust')
.outputFluids(Fluid.of("gtceu:carbon_dioxide",3000))
.blastFurnaceTemp(1173)
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_eu2o3')
.itemInputs('gtceu:euco3_dust')
.itemOutputs('gtceu:eu2o3_dust')
.outputFluids(Fluid.of("gtceu:carbon_dioxide",3000))
.blastFurnaceTemp(1173)
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_gd2o3')
.itemInputs('gtceu:gdco3_dust')
.itemOutputs('gtceu:gd2o3_dust')
.outputFluids(Fluid.of("gtceu:carbon_dioxide",3000))
.blastFurnaceTemp(1173)
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_tb2o3')
.itemInputs('gtceu:tbco3_dust')
.itemOutputs('gtceu:tb2o3_dust')
.outputFluids(Fluid.of("gtceu:carbon_dioxide",3000))
.blastFurnaceTemp(1173)
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_dy2o3')
.itemInputs('gtceu:dyco3_dust')
.itemOutputs('gtceu:dy2o3_dust')
.outputFluids(Fluid.of("gtceu:carbon_dioxide",3000))
.blastFurnaceTemp(1173)
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_ho2o3')
.itemInputs('gtceu:hoco3_dust')
.itemOutputs('gtceu:ho2o3_dust')
.outputFluids(Fluid.of("gtceu:carbon_dioxide",3000))
.blastFurnaceTemp(1173)
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_er2o3')
.itemInputs('gtceu:erco3_dust')
.itemOutputs('gtceu:er2o3_dust')
.outputFluids(Fluid.of("gtceu:carbon_dioxide",3000))
.blastFurnaceTemp(1173)
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_tm2o3')
.itemInputs('gtceu:tmco3_dust')
.itemOutputs('gtceu:tm2o3_dust')
.outputFluids(Fluid.of("gtceu:carbon_dioxide",3000))
.blastFurnaceTemp(1173)
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_yb2o3')
.itemInputs('gtceu:ybco3_dust')
.itemOutputs('gtceu:yb2o3_dust')
.outputFluids(Fluid.of("gtceu:carbon_dioxide",3000))
.blastFurnaceTemp(1173)
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_lu2o3')
.itemInputs('gtceu:luco3_dust')
.itemOutputs('gtceu:lu2o3_dust')
.outputFluids(Fluid.of("gtceu:carbon_dioxide",3000))
.blastFurnaceTemp(1173)
        .duration(10)
        .EUt(1920);

event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_y2o3')
.itemInputs('gtceu:yco3_dust')
.itemOutputs('gtceu:y2o3_dust')
.outputFluids(Fluid.of("gtceu:carbon_dioxide",3000))
.blastFurnaceTemp(1173)
        .duration(10)
        .EUt(1920);
event.recipes.gtceu.electric_blast_furnace('mcgougou:blast_ca')
.itemInputs('6x gtceu:quicklime_dust')
.itemOutputs('2x gtceu:aluminium_dust')
.outputFluids(Fluid.of("gtceu:ca_gas",3000))
.itemOutputs('3x gtceu:lvsuangai_dust')
.blastFurnaceTemp(1173)
        .duration(20)
        .EUt(1920);
event.recipes.gtceu.fluid_solidifier('mcgougou:sol_ca')
.inputFluids(Fluid.of("gtceu:ca_gas",1000))
.itemOutputs('gtceu:calcium_dust')
        .duration(20)
        .EUt(500);
// event.recipes.gtceu.test_generator('mcgougou:turbinerecipe_01')
//         .itemInputs('gtceust')
//         .itemOutputs('gtcedust')
//         .inputFluids( Fluid.of('gtceu:steam', 1000))
//         .outputFluids(Fluid.of("gtceuwater",1000))
//         .duration(20)
//         .EUt();
// event.forEachRecipe({ mod: 'gtceu' }, recipe => { 
//         try { 
//             var newDuration = recipe.get("duration") 
//             recipe.set("duration", newDuration/4) //遍历，处理时间/4
//         } catch (err) { 
//         }
//     })

})
const $EURecipeCapability = Java.loadClass("com.gregtechceu.gtceu.api.capability.recipe.EURecipeCapability");
ServerEvents.recipes(event => {
    event.forEachRecipe({ mod: 'gtceu' }, recipe => {
        try {
            let duration = recipe.get("duration");
            if (duration === undefined || duration <= 0) return;
 
            // 判断是否为发电配方：检查 tickOutputs 或 outputs 中是否包含 EU
            let isGenerator = false;
            let tickOutputs = recipe.get("tickOutputs");
            if (tickOutputs && tickOutputs.containsKey($EURecipeCapability.CAP)) {
                let euList = tickOutputs.get($EURecipeCapability.CAP);
                if (euList && !euList.isEmpty()) isGenerator = true;
            }
            if (!isGenerator) {
                let outputs = recipe.get("outputs");
                if (outputs && outputs.containsKey($EURecipeCapability.CAP)) {
                    let euList = outputs.get($EURecipeCapability.CAP);
                    if (euList && !euList.isEmpty()) isGenerator = true;
                }
            }
 
            // 如果不是发电配方，缩短时长
            if (!isGenerator) {
                let newDuration = Math.floor(duration / 10);
                recipe.set("duration", newDuration);
            }
        } catch (err) {
        }
    });
});